name: 🔒 Add site with 2FA
description: Request that a site that supports 2FA be added.
title: Add [site name]
labels: add site
body:
  - type: input
    id: name
    attributes:
      label: Site name
      description: Official name of the site
      placeholder: YouTube
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: Site URL
      description: Link to the main page
      placeholder: https://youtube.com
    validations:
      required: true

  - type: input
    id: doc
    attributes:
      label: Documentation URL
      description: |
        Link to documentation on how to enable 2FA on the site.
        Attach screenshots of the setup/login process if no public-facing documentation link is available, redacting any personal information.

  - type: checkboxes
    id: 2fa
    attributes:
      label: Supported 2FA methods
      description: Check every 2FA method that the site supports.
      options:
        - label: TOTP (RFC-6238, Google Authenticator)
        - label: Proprietary Software (Authy, Duo, etc.)
        - label: FIDO2/U2F/WebAuthn security keys
        - label: Proprietary hardware (Yubico OTP, RSA keys, etc.)
        - label: Phone calls
        - label: SMS tokens
        - label: Email tokens

  - type: checkboxes
    attributes:
      label: Eligibility
      description: |
        Check each box below to verify that the site meets our requirements for being listed.

        If a site does not meet all of these requirements, feel free to continue your issue submission.
        Leave any unmet requirements unchecked, and add any additional information or questions in the "Additional information" section below.
      options:
        - label: I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
        - label: The site is ranked within the top 200,000 sites on [Similarweb](https://www.similarweb.com/) or has a substantial social media following.
        - label: The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.
        - label: The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
          required: true
        - label: The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)
          required: true

  - type: textarea
    attributes:
      label: Additional information
      description: If you have any additional information to provide, please do so below.
