name: Replace Issue Title
on:
  issues:
    types:
      - opened
env:
  GH_TOKEN: ${{ github.token }}

jobs:
  replace:
    name: Replace Issue Title
    if: contains(toJson(github.event.issue.labels.*.name), 'add site') || contains(toJson(github.event.issue.labels.*.name), 'update site')
    runs-on: ubuntu-latest
    steps:
      - name: Issue Forms Body Parser
        id: parse
        uses: zentered/issue-forms-body-parser@v2.0.0
      - name: Extract site-name
        id: extract-site-name
        uses: 2factorauth/issue-title-action@master
        with:
          repository: ${{ github.repository }}
          issue_number: ${{ github.event.issue.number }}
          data: ${{ toJSON(steps.parse.outputs.data) }}
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: "${{ toJSON(github.event.issue.labels) }}"
          similarweb_key: ${{ secrets.SIMILARWEB_KEY }}
