name: Site Tests

on:
  pull_request:
    paths:
      - _data/*.yml

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Site Tests
    steps:

    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1

      # For now only twitter gem is needed. TODO: move to bundler
    - name: Install dependencies
      run: gem install twitter

    - name: Check Twitter handles
      run: bash twitter.sh
      working-directory: .tests
      env:
        access_key: ${{ secrets.twitter_access_key }}
        access_secret: ${{ secrets.twitter_access_secret }}
        consumer_key: ${{ secrets.twitter_consumer_key }}
        consumer_secret: ${{ secrets.twitter_consumer_secret }}

    - name: Check Alexa ranking
      run: ./alexa.sh
      working-directory: .tests
      env:
        access_key: ${{ secrets.alexa_access_key }}
        access_secret: ${{ secrets.alexa_secret}}
