name: Publish
on:
  push:
    branches:
      - master

concurrency:
  group: 'publish'
  cancel-in-progress: true

jobs:
  publish:
    name: Build and Publish files
    if: github.repository == '2factorauth/twofactorauth'
    permissions:
      pages: write
      id-token: write
    environment: production
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: '3.0'
      - name: Generate API files
        run: |
          mkdir -p api/v3
          ./scripts/APIv3.rb
      - name: Publish changes to Algolia
        run: bundle exec ruby ./scripts/Algolia.rb
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_INDEX_NAME: ${{ vars.ALGOLIA_INDEX_NAME }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
      - uses: crazy-max/ghaction-import-gpg@v5
        id: pgp
        with:
          gpg_private_key: ${{ secrets.PGP_KEY }}
          passphrase: ${{ secrets.PGP_PASSWORD }}
      - name: Sign API files
        run: bundle exec ruby scripts/Sign.rb
        env:
          PGP_PASSWORD: ${{ secrets.PGP_PASSWORD }}
          PGP_KEY_ID: ${{ steps.pgp.outputs.keyid }}
      - name: Prepare publish directory
        run: |
          mkdir -p public/icons
          cp -r api/. public/
          cp -r img/. public/icons/
          cp robots.txt public/
      - uses: actions/upload-pages-artifact@v1
        with:
          path: public/
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
      - name: Send webhook to Cloudflare
        run: curl -X POST -IL "${{ secrets.WEBHOOK }}" -o /dev/null -w '%{http_code}\n' -s
