name: Rubocop

on: [push, pull_request]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    name: Rubocop
    steps:
      - uses: actions/checkout@v2.1.0

      - uses: actions/cache@v1.1.2
        with:
          path: vendor/cache
          key: ${{ runner.os }}-bundle-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-bundle-

      - uses: actions/setup-ruby@v1

      - name: Run Bundler
        run: |
          bundle config set path 'vendor/cache'
          bundle config set cache_all true
          bundle install --jobs 4 --retry 3
          [ -d "vendor/cache" ] || { bundle package; }

      - name: Run Rubocop
        run: bundle exec rake rubocop
