name: Rubocop

on:
  push:
    paths: verify.rb
  pull_request:
    paths: verify.rb

jobs:
  rubocop:
    runs-on: ubuntu-latest
    name: Rubocop
    steps:
    - uses: actions/checkout@v1

    - name: Get Cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-bundler

    - name: Install requirements
      run: sudo snap install ruby --classic

    - name: Run Bundler
      if: steps.cache.outputs.cache-hit != 'true'
      run: bundle install --path vendor/bundle

    - name: Run Rubocop
      run: ruby bundle exec rake rubocop
